INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 2 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 6 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 4 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 5 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 10 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для основы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Основное');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 8 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 7 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для глазури');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 3 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 20 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 12 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Болоньезе ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Бешамель');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для декора');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шариков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для кекса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 1 порцию');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для украшения');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для соуса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для маринада');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для заправки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Бисквит');
INSERT INTO public.ingredient_groups ("name") VALUES ('Начинка');
INSERT INTO public.ingredient_groups ("name") VALUES ('Крем');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 30 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для кляра');
INSERT INTO public.ingredient_groups ("name") VALUES ('Конфеты');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для желе');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для ванильного пудинга');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадного пудинга');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 15 порции');
INSERT INTO public.ingredient_groups ("name") VALUES (' Начинка и соус');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для бисквита');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для коржей');
INSERT INTO public.ingredient_groups ("name") VALUES ('Тесто');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для торта');
INSERT INTO public.ingredient_groups ("name") VALUES ('Рулька');
INSERT INTO public.ingredient_groups ("name") VALUES ('Соус');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 18 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 11 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сырного суфле');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для фарша');
INSERT INTO public.ingredient_groups ("name") VALUES ('Основные ингредиенты');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 9 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 50 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 25 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для подачи');
INSERT INTO public.ingredient_groups ("name") VALUES ('Кроме того');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для бульона');
INSERT INTO public.ingredient_groups ("name") VALUES (' Для теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для заливки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для соуса маринара ризотто');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для карамели');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для курицы тандури');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для кабачков в соусе');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 14 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сметанного соуса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Биточки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для гренок');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первого слоя глазури');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для крутонов');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для блинов');
INSERT INTO public.ingredient_groups ("name") VALUES ('По желанию');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для гарнира');
INSERT INTO public.ingredient_groups ("name") VALUES ('Глазурь');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для опары');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для соуса Бешамель');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для  кекса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Сэндвич');
INSERT INTO public.ingredient_groups ("name") VALUES ('Основа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Начинка арахис-джем');
INSERT INTO public.ingredient_groups ("name") VALUES ('Начинка яблоко');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для омлета');
INSERT INTO public.ingredient_groups ("name") VALUES ('Клаб Сэндвич');
INSERT INTO public.ingredient_groups ("name") VALUES ('Сырный Сэндвич');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 16 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смазки верха');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для соуса ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 28 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для крема № 1');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для королевской глазури из яичных белков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для королевской глазури из безе порошка');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для песочного теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для безе');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 40 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для полосок');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для фруктового слоя');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки № 1');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки № 2');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смазки пирожков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пчёл');
INSERT INTO public.ingredient_groups ("name") VALUES ('Прослойка');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для творожного слоя');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для штрейзеля');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пропитки верхнего коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для кабачкового теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для чипеток (теста)');
INSERT INTO public.ingredient_groups ("name") VALUES ('Красители');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сливочного крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для салата');
INSERT INTO public.ingredient_groups ("name") VALUES ('Первый ягодный слой');
INSERT INTO public.ingredient_groups ("name") VALUES ('Второй ягодный слой');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для супа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для люля-кебаб');
INSERT INTO public.ingredient_groups ("name") VALUES ('Мясо');
INSERT INTO public.ingredient_groups ("name") VALUES ('Маринад');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для меренги');
INSERT INTO public.ingredient_groups ("name") VALUES ('Пряники');
INSERT INTO public.ingredient_groups ("name") VALUES ('Соус томатный');
INSERT INTO public.ingredient_groups ("name") VALUES ('Фрикадельки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Запеканка');
INSERT INTO public.ingredient_groups ("name") VALUES ('Мясная начинка');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для лепешек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 24 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для посыпки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для курицы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Тесто (указано на 2 пиццы диаметром 33-35см).');
INSERT INTO public.ingredient_groups ("name") VALUES ('Начинка (указано на 1 пиццу диаметром 33-35см)');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для верха');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для подливы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Опара');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первого коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второго коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для суфле');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сердцевинок');
INSERT INTO public.ingredient_groups ("name") VALUES ('Шоколадно-банановый');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ягодный');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для миндально-карамельной заливки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для засахаренных кусочков апельсина');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для апельсинового крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смазки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для панировки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для котлет');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сметанного крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для заварного крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для украшения и пропитки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для соуса тартар');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для дрожжевой болтушки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 35 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для вафель');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадных муссов');
INSERT INTO public.ingredient_groups ("name") VALUES ('Персиковая начинка');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадной массы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для блинчиков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для светлого теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для темного теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для картофельной массы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Вариант 2');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для творожного теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадного теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для тарталеток');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для теста (на один корж)');
INSERT INTO public.ingredient_groups ("name") VALUES ('Наполнители');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сундучка');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пирога');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для одного коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Дополнительно');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для намазки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для панкейков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смеси с зеленью');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смеси с ванилью');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смеси с медом');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для груш');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для гранатового соуса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смазывания');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для капустной начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для рассола');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для зраз');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для макового слоя');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадного слоя');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для заправки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для светлого суфле');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для роллов');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пропитки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шашлыка');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пирожных');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для бланманже');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для лапши');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для рулета');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для картофельной начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для творожных шариков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сиропа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сметанного слоя');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сыра');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадного крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для инвертного сиропа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для клубничного слоя');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первого слоя');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второго слоя');
INSERT INTO public.ingredient_groups ("name") VALUES ('По 1/3 стакана');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сырного слоя');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для крошки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для фрикаделек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадной глазури');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для карамельного соуса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шага 1');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шага 2');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для яиц');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для брауни');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для жаркого');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для печенья');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для третьего коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для топпинга');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадного коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для дрожжевого теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для крем-соуса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для приправы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для чесночного соуса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для помадки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для лосося');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второй начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки 1');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шубки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для чесночного масла');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для букета гарни');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для теста 1');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для теста2');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для творожного крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пудингового крема с желе');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сырных шариков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для масляно-кофейного крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для куриного филе');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для креветок');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для покрытия');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для лимонного курда');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для капкейков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для томатного соуса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для каши');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для   бисквита');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для мучного блока');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для масляного блока');
INSERT INTO public.ingredient_groups ("name") VALUES ('На молоке');
INSERT INTO public.ingredient_groups ("name") VALUES ('На сливках');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для светлых коржей');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадных коржей');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первого этапа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второго этапа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для греческих лепешек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пудинга');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для обсыпки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для ванильного крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для омлетных блинчиков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для мучной крошки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для творожной начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для гремолата');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смазывания верха');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первой порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для соуса тар-тар');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для белковой массы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для меренгов');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для кофейного крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для хрустящей корочки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для тефтелей');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для нудлей');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для 1 литра рассола');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для основания');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для заполнения');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для корзинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для желтого омлета');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для красного омлета');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для зеленого омлета');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для мясной начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для оладий');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первого крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второго крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для абрикосового пюре');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадного ганаша');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для миндальной пасты');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смазывания пирожков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сальса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первого теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второго теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Овощи');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для булочек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для дипа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для баклажанов');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сырной начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для соуса бешамель');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для жура');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для панна котты');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для корзиночек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для швейцарской меренги');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для темной глазури');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сгущенки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Цитрусовые в сиропе');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для коржа брауни');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для миндального бисквита джаконда');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для мусса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для маринования');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для грибной начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для ореховой нуги');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для профитролей');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пломбира');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для творожно-кокосовых шариков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первой смеси');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второй смеси');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для 1 желе');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для 1 коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для 2 коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для 3 коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для кудряшек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пудингового крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для яблочного крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для белой глазури');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для черной глазури');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для маковой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для ореховой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для луковой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки с огурцами');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для миндального крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для макового коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для орехового коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для соуса Дзадзики');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для лимонно-малинового курда');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первой массы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второй массы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первой опары');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второй опары');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для масляного пласта');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для гуляша');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для творожной части');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки 2');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки 3');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки 4');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки 5');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для макового бисквита');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для песочной основы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для оливкового салата с фетой');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для запиканки-суфле');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для светлого коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для темного коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для белого мусса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для малинового желе');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки (вариант 1) ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для льезона');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для соуса «Сальса Верде»');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для карамельно-сливочного крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для малинового ганаша');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для малинового мармелада');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для 1-го желе');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадно-карамельного ганаша');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для взбитых сливок');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для фисташкового крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для крема из молочного шоколада и нуги');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для орехового мусса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для картофельных ватрушек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смеси пряностей');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки №1');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки №2');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для прослойки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадной начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для майонеза');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для хумуса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для обваливания');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для грибного соуса');
INSERT INTO public.ingredient_groups ("name") VALUES ('1 чизкейк');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для блинчика');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для бананового мороженого');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для красных блинов');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для ягодного мороженого');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для миндального мороженого');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для батончика');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для творожной основы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для риса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для мяса ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для приправы 5 специй');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для кофейного желе');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для апельсинового конфитюра');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для ганаша');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для  соуса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для кокосовых шариков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для оформления');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для маринада №1');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для маринада №2');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для копчения');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для коричневой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для картопляников');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для коржа с изюмом');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для домашней лапши');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для банановых блинов');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки и украшения');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для галушек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Коржи');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сухариков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пасты');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сахарной глазури');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шукрут');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для нижнего коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для верхнего коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для зефира');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для гранатовой малассы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для кексов');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сметанной глазури');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для мороженого');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для белого крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадного соуса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для обмакивания');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для подготовки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для клецек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для французской меренги');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для ванильного шантийи');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для клубничного сиропа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сахарного сиропа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пропитки печенья');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для трубочек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для хрустящего слоя с пралине');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пралине');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для клюквенного компота');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для ванильного крем-мусс');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для клюквенного крем-мусс');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для медового коржа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для абрикосового крема');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для вафли');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сальсы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Или для грибной начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первого способа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второго способа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для третьего способа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для четвертого способа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пятого способа');
INSERT INTO public.ingredient_groups ("name") VALUES (' специи');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для жарки');
INSERT INTO public.ingredient_groups ("name") VALUES (' для украшения');
INSERT INTO public.ingredient_groups ("name") VALUES ('Начинка №1');
INSERT INTO public.ingredient_groups ("name") VALUES ('Начинка №2');
INSERT INTO public.ingredient_groups ("name") VALUES ('Маринад №1');
INSERT INTO public.ingredient_groups ("name") VALUES ('Маринад №2');
INSERT INTO public.ingredient_groups ("name") VALUES (' для шоколадной начинки');
INSERT INTO public.ingredient_groups ("name") VALUES (' для коржей');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для крема №1');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для крема №2');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для крема №3');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для бисквита ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 45 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для мяса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для запеченных бананов');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для тёмной глазури');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для закуски (начинка) ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для теста № 1');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для теста № 2');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 39 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Слоеные рулетики ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Конфеты из творога');
INSERT INTO public.ingredient_groups ("name") VALUES ('Классический сэндвич');
INSERT INTO public.ingredient_groups ("name") VALUES ('Сэндвич в конвертике');
INSERT INTO public.ingredient_groups ("name") VALUES ('Закуска в конвертике из лаваша');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для бисквитного теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Сэндвичи');
INSERT INTO public.ingredient_groups ("name") VALUES ('Яичный рулет');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пшеничной закваски');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 36 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смазывания булочек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Гренки с яйцом');
INSERT INTO public.ingredient_groups ("name") VALUES ('Бутерброды с соусом под сыром');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для гнездышек');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для песочного верха');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для заварного теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для третьей начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для четвертой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пятой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шестой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для седьмой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для восьмой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для девятой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для десятой начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 13 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 17 порции');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первого варианта');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для слоения теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для смазывания формы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для гренок с сыром ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для печенья с сыром');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадных кубиков');
INSERT INTO public.ingredient_groups ("name") VALUES (' для начинки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первого бульона');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второго бульона');
INSERT INTO public.ingredient_groups ("name") VALUES ('Слойки несладкие');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для зеленых блинов');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки (указаны ингредиенты для каждого хачапури )');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для гнезд с макаронами');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для подливки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Начинка для вареников');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для панировки ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Маринад ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второго варианта');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для домашнего майонеза');
INSERT INTO public.ingredient_groups ("name") VALUES ('Фарш');
INSERT INTO public.ingredient_groups ("name") VALUES ('Томатная заправка');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для соуса песто');
INSERT INTO public.ingredient_groups ("name") VALUES ('Пропитка коржей');
INSERT INTO public.ingredient_groups ("name") VALUES ('Соус Бешамель');
INSERT INTO public.ingredient_groups ("name") VALUES ('Сироп');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для чипса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пончиков');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для пасты ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Свинина Чашу');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для итальянской меренги');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для Меренги');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для белого теста');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для  бисквита');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для сырной массы');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для начинки ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Заправка');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для нижнего слоя');
INSERT INTO public.ingredient_groups ("name") VALUES ('Капкейки');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для ризотто');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для рулетов');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для закваски');
INSERT INTO public.ingredient_groups ("name") VALUES ('Соус ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Панировка');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для конфи');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для кокосового слоя');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для первого слоя мусса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для второго слоя мусса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для третьего слоя мусса');
INSERT INTO public.ingredient_groups ("name") VALUES ('Гарнир');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для фарша ');
INSERT INTO public.ingredient_groups ("name") VALUES ('Панна Котта');
INSERT INTO public.ingredient_groups ("name") VALUES ('Для шоколадного сиропа');
INSERT INTO public.ingredient_groups ("name") VALUES ('Манник');
INSERT INTO public.ingredient_groups ("name") VALUES ('Яичная смесь');
INSERT INTO public.ingredient_groups ("name") VALUES ('Дрожжевое тесто');
INSERT INTO public.ingredient_groups ("name") VALUES ('Сырное тесто');
INSERT INTO public.ingredient_groups ("name") VALUES ('Ингредиенты на 19 порции');
